/**
 * Shared package: deterministic game engine and schemas for API and client.
 * Import from "@app/shared".
 * Structure: api/ (HTTP contract types), map/ (dungeon generation), game/ (engine + snapshot schemas), rng/.
 */

export {
	buildDecorationLayer,
	buildGroundLayer,
	buildWallLayer,
	buildWaterMask,
	BLOCKING_DECORATION_TYPES,
	DEFAULT_BSP_ROOM_INSET,
	DEFAULT_CAVE_FLOOR_CHANCE,
	DEFAULT_DECORATION_WEIGHTS,
	DEFAULT_FLOOR_THEME,
	DEFAULT_MAP_ALGORITHM,
	DEFAULT_FLOOR_CONFIG,
	DEFAULT_MAP_HEIGHT,
	DEFAULT_MAP_WIDTH,
	DEFAULT_SCATTER_CHANCE,
	TILE_TYPE,
	generateMap,
	isCellWalkable,
	wouldStayConnected,
	type BuildDecorationLayerResult,
	type GeneratedMap,
	type DecorationType,
	type MapGenAlgorithm,
	type MapGenConfig,
	computeOpacityMask,
	computeVisibility,
	mergeExplored,
} from "./map";
export { createRng, createInitialRngState, createRngFromState, type Rng } from "./rng";

export {
	ActionSchema,
	AttackActionSchema,
	MoveActionSchema,
	actorKind,
	applyAction,
	applyActionWithDerivedContext,
	buildGameStateFromPersisted,
	createActionContext,
	createEmptyFloorState,
	createInitialState,
	DEFAULT_HERO_INIT,
	findAdjacentWalkable,
	gameStateToPersisted,
	getActorAtIdx,
	getAdjacentIndices,
	getHero,
	computeWalkableMaskForFloor,
	idxToXY,
	regenerateBaseMaps,
	resetMonsterCounter,
	spawnMonster,
	xyToIdx,
	MAP_GEN_VERSION,
	VISION_RADIUS,
	ActorAttributesSchema,
	ActorDefSchema,
	ActorsByIdSchema,
	ActorSchema,
	ActorSkillStateSchema,
	FloorStateSchema,
	PersistedDynamicStateSchema,
	RngStateSchema,
	type Action,
	type ActionLogEntry,
	type Actor,
	type ActorAttributes,
	type ActorDef,
	type ActorId,
	type ActorSkillState,
	type ApplyActionContext,
	type ApplyActionResult,
	type AttackAction,
	type BaseLayerFloor,
	type GameEvent,
	type GameSessionDoc,
	type GameSnapshotDoc,
	type GameState,
	type HeroInit,
	type MonsterInit,
	type MoveAction,
	type PersistedDynamicState,
} from "./game";

export {
	abilityModifier,
	computeUnarmoredAC,
	resolveAttack,
	rollD20,
	rollDice,
	UNARMED_WEAPON,
	type AttackResult,
	type WeaponDice,
} from "./combat";

export { createGameBodySchema, type CreateGameBody, type HealthResponse } from "./api";
