/**
 * Shared package: deterministic game engine and schemas for API and client.
 * Import from "@app/shared".
 * Tunables live in `./config` and are re-exported here; domain barrels (`map/`, `game/`, …) expose behaviour only.
 */

export {
	CONFIG,
	GAME_CONFIG,
	MAP_CONFIG,
	COMBAT_CONFIG,
	SKILLS_CONFIG,
	MAP_GEN_VERSION,
	VISION_RADIUS,
	XP_PER_LEVEL,
	BASE_NPCS_PER_FLOOR,
	STATUS_HOOKS,
	DAMAGE_TYPES,
	UNARMED_WEAPON,
	DEFAULT_BSP_PARAMS,
	DEFAULT_CAVE_PARAMS,
	DEFAULT_DECORATION_WEIGHTS,
	DEFAULT_FLOOR_THEME,
	DEFAULT_MAP_ALGORITHM,
	DEFAULT_FLOOR_CONFIG,
	DEFAULT_MAP_HEIGHT,
	DEFAULT_MAP_WIDTH,
	DEFAULT_SCATTER_CHANCE,
	DEFAULT_SHAPE_VOID_TARGET,
	TILE_TYPE,
	FLOOR_THEMES,
	FLOOR_CONFIGS,
} from "./config";
export type { FloorTheme, DamageType } from "./config";

export {
	buildDecorationLayer,
	buildGroundLayer,
	buildWallLayer,
	buildWaterMask,
	BLOCKING_DECORATION_TYPES,
	generateMap,
	isCellWalkable,
	wouldStayConnected,
	type AnalyzedRoom,
	type AlgorithmParams,
	type ArenaParams,
	type BossRules,
	type BspParams,
	type BuildDecorationLayerResult,
	type CaveParams,
	type DecorationType,
	type EncounterDef,
	type EncounterEntry,
	type EncounterTableEntry,
	type FloorConfig,
	type HybridParams,
	type MapGenAlgorithm,
	type RawMap,
	type RoomTag,
	type VaultDef,
	type VaultPlacement,
	computeOpacityMask,
	computeVisibility,
	mergeExplored,
	findExitIdx,
	analyzeRooms,
	injectVaults,
	type RegenerateOptions,
} from "./map";
export { createRng, createInitialRngState, createRngFromState, type Rng } from "./rng";

export {
	ActionSchema,
	AttackActionSchema,
	MoveActionSchema,
	RerollSkillChoiceActionSchema,
	SelectSkillChoiceActionSchema,
	UseSkillActionSchema,
	actorKind,
	applyAction,
	applyActionWithDerivedContext,
	applyGodModePostProcess,
	buildGameStateFromPersisted,
	createActionContext,
	createEmptyFloorState,
	createInitialState,
	DEFAULT_HERO_INIT,
	DIRECTION_DELTA,
	findAdjacentWalkable,
	gameStateToPersisted,
	getActorAtIdx,
	getAdjacentIndices,
	getAdjacentIndices8,
	getHero,
	computeWalkableMaskForFloor,
	idxToXY,
	generateSkillOffers,
	regenerateBaseMaps,
	resetNpcCounter,
	spawnNpc,
	xyToIdx,
	AbilityNameSchema,
	ActiveEffectSchema,
	CombatAdjustmentsSchema,
	ActorAttributesSchema,
	ActorDefSchema,
	ActorsByIdSchema,
	ActorSchema,
	ActorSkillStateSchema,
	FloorStateSchema,
	NpcAIStateSchema,
	PersistedDynamicStateSchema,
	RngStateSchema,
	PassiveDamageBonusSchema,
	PendingInteractionSchema,
	type Action,
	type ActionLogEntry,
	type Direction,
	type RerollSkillChoiceAction,
	type SelectSkillChoiceAction,
	type AbilityName,
	type ActiveEffect,
	type CombatAdjustments,
	type Actor,
	type ActorAttributes,
	type ActorDef,
	type ActorId,
	type ActorSkillState,
	type ApplyActionContext,
	type ApplyActionResult,
	type AttackAction,
	type ClassSkillPools,
	type BaseLayerFloor,
	type FloorState,
	type GameEvent,
	type GameSessionDoc,
	type GameSnapshotDoc,
	type GameState,
	type HeroInit,
	type NpcInit,
	type MoveAction,
	type PassiveDamageBonus,
	type PendingInteraction,
	type PersistedDynamicState,
	type SkillDamageEvent,
	type UseSkillAction,
	isSkillDamageEvent,
} from "./game";

export {
	applyPassiveSkill,
	getTilesInLine,
	getTilesInCone,
	hasActiveEffect,
	resolveSkill,
	ActiveSkillDefinitionSchema,
	ActiveSkillEffectDescriptorSchema,
	PassiveSkillDefinitionSchema,
	PassiveSkillEffectDescriptorSchema,
	SkillDefinitionSchema,
	type ActiveSkillDefinition,
	type ActiveSkillEffectDescriptor,
	type ApplyStatusEffect,
	type PassiveSkillDefinition,
	type PassiveSkillEffectDescriptor,
	type SkillDefinition,
} from "./skills";

export {
	abilityModifier,
	computeUnarmoredAC,
	resolveAttack,
	rollD20,
	rollDice,
	proficiencyBonusFromLevel,
	proficiencyBonusFromChallengeRating,
	computeSavingThrowDC,
	resolveSavingThrow,
	isActorProficientInSavingThrow,
	getActorProficiencyBonus,
	type AttackResult,
	type WeaponDice,
} from "./combat";

export { createGameBodySchema, type CreateGameBody, type HealthResponse } from "./api";

export {
	applyEquipment,
	buildEquipmentSlots,
	type AffixDef,
	type ItemDef,
	type ItemInstance,
	type ItemRarity,
	type LootDrop,
	type LootTable,
	type WeaponItemDef,
	type ArmorItemDef,
	type ShieldItemDef,
	type AccessoryItemDef,
	type NaturalWeapon,
	type EquipmentSlots,
	type WeaponCategory,
	type ArmorCategory,
} from "./items";
